export const randomPrompts = [
  "a cozy cabin in the woods surrounded by glowing bioluminescent plants, at night, digital art",
  "a steampunk airship flying over a city with towering clockwork skyscrapers, sunset lighting, digital art",
  "a jellyfish floating through a cityscape like a hot air balloon, surreal digital art",
  "a Victorian-style robot playing a grand piano in a candlelit room, oil painting",
  "a whimsical tea party in the clouds, with animals like rabbits and foxes dressed in formal attire, pastel colors",
  "a futuristic monorail gliding through a neon-lit jungle, digital art",
  "a giant whale flying through the sky with a city on its back, fantasy art",
  "a medieval castle made of ice, glowing softly under the northern lights, digital art",
  "a cyberpunk café bustling with humanoid robots and humans, neon reflections, digital art",
  "a dragon curled up like a cat sleeping on a pile of gold, digital painting",
  "a magical library where books are floating and glowing, digital art",
  "a UFO hovering over a serene lavender field at sunset, photography",
  "a robot gardener tending to plants in a futuristic greenhouse, digital art",
  "a phoenix rising from a lake surrounded by mist, oil painting",
  "a group of penguins wearing bow ties and hats, sliding down an icy hill, cartoon style",
  "a flying car chase through a futuristic city with vibrant holographic advertisements, digital art",
  "a mysterious portal in the middle of a desert, surrounded by glowing runes, fantasy art",
  "a peaceful alien village nestled in a crater, under a vibrant alien sky, digital art",
  "a lion made entirely of glowing stars and constellations, standing majestically, digital art",
  "a surreal landscape of giant floating rocks with waterfalls cascading off the edges, digital art",
  "a futuristic underwater city with glowing buildings, digital art",
  "a time-traveling train speeding through a swirling vortex, digital art",
  "a treehouse village built in a giant ancient tree, glowing lanterns lighting the paths, digital art",
  "a samurai robot meditating under a cherry blossom tree, digital art",
  "a floating market on a sky river, with colorful stalls and boats, digital art",
  "a knight in shining armor riding a giant snail through an enchanted forest, digital art",
  "a mysterious wizard casting a spell in a stormy mountaintop, digital art",
  "a celestial goddess surrounded by planets and galaxies, ethereal digital art",
  "a cybernetic tiger stalking through a neon jungle, digital art",
  "a quaint village of houses shaped like teapots and mushrooms, whimsical illustration",
  "a futuristic skyscraper made of glass and greenery, glowing softly at night, digital art",
  "a serene beach scene with a futuristic twist, including glowing seashells and bioluminescent waves, digital art",
  "a tiny robot fishing on the edge of a floating island in the sky, digital art",
  "a magical carousel with animals made of crystal, spinning in a moonlit forest, digital art",
  "an ancient stone temple with a holographic deity statue in the center, digital art",
  "a panda samurai battling shadowy figures under a blood moon, digital art",
  "a surreal dreamscape with melting clocks and floating islands, inspired by Salvador Dalí, digital art",
  "a cityscape where buildings are shaped like musical instruments, digital art",
  "a futuristic biker gang riding glowing motorcycles through a neon desert, digital art",
  "a sentient tree with glowing eyes guarding an ancient forest, fantasy art",
  "a futuristic airport where the planes look like giant birds, digital art",
  "a friendly alien family having a picnic on a distant planet with a vibrant alien landscape, digital art",
  "a glowing jellyfish city floating in a deep ocean trench, digital art",
  "a surreal chessboard landscape with giant chess pieces in the distance, digital art",
  "a steam-powered dragon flying over a Victorian city, digital art",
  "a celestial fox running through the night sky, leaving trails of stardust, digital art",
  "a glowing crystal cave with a mysterious figure exploring its depths, digital art",
  "a robot orchestra performing in a grand futuristic hall, digital art",
];
